# Generated by Django 6.0.6 on 2026-07-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(db_index=True, max_length=40)),
                ('role', models.CharField(db_index=True, default='any', max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('preview', models.TextField()),
                ('payload', models.JSONField()),
                ('source', models.CharField(default='curated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
